---
title: ""
author: "Duc-Quang Nguyen | swissinfo.ch"
date: " 2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---

## Data
* [PX Offre cinématographique et demande selon région linguistique, type de projection (2D/3D), version de langue et genre](https://www.pxweb.bfs.admin.ch/Selection.aspx?px_language=fr&px_db=px-x-1602010000_200&px_tableid=px-x-1602010000_200\px-x-1602010000_200.px&px_type=PX)

```{r setup, include=FALSE}
translation.file <- "input/movies in Swiss cinema - Sheet1.csv"
annotation.file <- "input/movies in Swiss cinema - annotations.csv"

facet_height <- 2.7

# country.sub <- c('- EU 28 - total', '- Other countries - total', '- Asia - total', '- Latin America - total', "Switzerland", "United States", "France", "Germany", "United Kingdom")
country.sub <- c('- EU 28 - total', '- Other countries - total', '- Asia - total', '- Latin America - total', "Switzerland", "United States")
country.check.sub <- c('- EU 28 - total', '- Other countries - total', '- Asia - total', '- Latin America - total', "......Switzerland", "......United States")

groups <- data.frame(
  key = c("- Asia - total", "- EU 28 - total", "- Latin America - total", "- Other countries - total", "France", "Germany", "Switzerland", "United Kingdom", "United States"),
  name = c("Asia", "EU 28", "Latin America", "Other countries", "France", "Germany", "Switzerland", "United Kingdom", "United States"),  
  order = c(4, 3, 5, 6, 7, 8, 1, 9, 2),
  color = c("#ac673e", "#333366", "#666633", "#336666", "#336666", "#448888", "#ab3d3f", "#55aaaa", "#3a9736")
)
groups <- groups[order(groups$order),]

vars.ordered <- c(
  'nFilms', 'screeningByFilm', 'admissionByScreening',
  'share_doc', 'share_fic', 'share_ani', 
  'share_dubbed', 'share_3d'
)
names(vars.ordered) <- c('1', '1', '1', '2', '2', '2', '3', '3')
  
px.file <- "data/px-x-1602010000_200.px"

library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)
library(ggiraph)

### Getting data in packages
library(pxR)

### Interactive 
library(htmltools)
library(shiny)
library(swiRcharts)

### Misc stuff
#require(classInt)
#require(viridis)
```

```{r load & translate, include = F}
txt <- loadTranslation(translation.file)
annot <- read.csv(annotation.file, stringsAsFactors = F)

px.read <- read.px(px.file)
data <- px.read$DATA[[1]]

# get the French terms
en <- px.read$VALUES.en.
de <- px.read$VALUES

colnames(data)[-ncol(data)] <- rev(names(en))

## helper to translate PX file
translate <- function(colname = 'Result.variable', data, en, de) {
  # find which colname idx
  i <- which(names(en) == colname)
  # split single string to a string vector
  translations <- unlist(strsplit(en[[i]], '", ?"'))
  stopifnot(length(translations) == length(de[[i]]))
  
  # match each term of the data to the levels
  idx <- match(data[[colname]], de[[i]])
  stopifnot(all(!is.na(idx)))
  
  factor(translations[idx])
}
# apply translation
for(coln in colnames(data)[-ncol(data)]) {
  data[,coln]<- translate(coln, data, en, de)
}
data.all <- data
```

```{r wrangle, include = F}
data %<>% filter(`Language.region` == "Total Switzerland" , 
                `All.films...new.releases` == "All films released") %>%
  select(-`Language.region`, - `All.films...new.releases`)

# get parent country of origin region
idx.reg <- grep(" - total", data$`Country.of.origin`)
idx.reg2 <- findInterval(1:nrow(data), idx.reg)
data[idx.reg2 != 0, 'region'] <- data[idx.reg[idx.reg2], 'Country.of.origin']

# sum data for all years
data %<>% group_by(`Result.variable`, `Language.version...screening.type...genre`, `Country.of.origin`, region) %>% 
  dplyr::summarise(value = sum(value)) %>% ungroup()

# add a column with the total films/admissions/entry by country
totals <- data %>% group_by(`Country.of.origin`, `Result.variable`) %>% 
  dplyr::summarise(
    tot_byCountry_film = value[which(`Language.version...screening.type...genre` == "Total of films")]
    ) %>%
  ungroup()

# remove the rows totals, but keep it in grand.totals for check
grand.totals <- data %>% 
  filter(`Language.version...screening.type...genre` == "Total of films", `Country.of.origin` == "Country of origin - Total" ) %>%
  select(-`Language.version...screening.type...genre`, -`Country.of.origin`, -region) %>%
  dplyr::rename(tot = value)
data %<>% filter(`Language.version...screening.type...genre` != "Total of films", `Country.of.origin` != "Country of origin - Total" )
# add column total
data <-  left_join(data, totals)


## explore the top country of origin
ori.top <- data %>% filter(`Result.variable` == "Admissions") %>% 
  group_by(`Country.of.origin`) %>% dplyr::summarise(totAdm = sum(value)) %>%
  ungroup() %>% arrange(desc(totAdm))

reg.top <- data %>% filter(`Result.variable` == "Admissions") %>% 
  group_by(`region`) %>% dplyr::summarise(totAdm = sum(value)) %>%
  ungroup() %>% arrange(desc(totAdm))

# quick exploration of the top countries
#data[grep(" - total", data$`Country.of.origin`),] %>% select( Country.of.origin) %>% unlist(use.names = F) %>% unique()
#grepl("......", data$`Country.of.origin`, fixed = T)

# Create a data.frame with all countries, their geo regions
countries <- data[grepl("......", data$`Country.of.origin`, fixed = T), 'Country.of.origin'] %>% unlist(use.names = F) %>% unique() %>% as.character()
countries <- data.frame(country = gsub("......", "", countries, fixed = T), country.original = countries, iso2c = countrycode(countries, "country.name", "iso2c"))

## map the iso2 and clean up
idx <- match(data$`Country.of.origin`, countries$country.original)
data <- cbind(data, countries[idx,c('iso2c', 'country')]) %>% 
  dplyr::rename(variable = `Result.variable`, type = `Language.version...screening.type...genre`, countryOri = `Country.of.origin`)

data$group <- ifelse(data$country %in% country.sub, as.character(data$country), as.character(data$region))

## TODO remove country from region values.....

## Filter by country or region subset
dat <- data[data$countryOri %in% country.sub | data$country %in% country.sub,]

#### check !!
check.tot <- dat %>% filter(countryOri %in% country.check.sub) %>% group_by(variable) %>% 
  dplyr::summarise(tot = sum(unique(tot_byCountry_film)))
stopifnot(identical(check.tot, grand.totals %>% dplyr::rename(variable = `Result.variable`)))

# more cleanup
dat %<>% select(-region, -iso2c, -country)
```

```{r explore, include=FALSE}
## Get overal numbers
# Number of movies by group, Number of projections,  Number of admissions
dd <- dat %>% group_by(variable, group) %>%
  dplyr::summarise(value = tot_byCountry_film[1] ) %>% 
  ungroup() %>% tidyr::spread(variable, value) %>%
  dplyr::rename(nAdmissions = Admissions, nFilms = `Number of films`, nScreenings = `Number of screenings`)

# Number of movies: animations, doc, fiction by number of movies
dd2 <- dat %>% filter(variable == "Number of films") %>% group_by(group) %>% 
   dplyr::summarise(ani = value[type == 'Animated films'], doc =  value[type == 'Documentaries'], fic =  value[type == 'Feature films']) %>% 
  ungroup()

# Admissions: dubbed, 3D
dd3 <- dat %>% filter(variable == "Admissions") %>% group_by(group) %>% 
   dplyr::summarise(d3 = value[type == '3D screenings'], dubbed = value[type == 'Dubbed version']) %>% 
  ungroup()

# join
dd <- left_join(left_join(dd, dd2), dd3)

## compute share & average
dd$screeningByFilm <- dd$nScreenings / dd$nFilms
dd$admissionByScreening <- dd$nAdmissions / dd$nScreenings

dd$share_3d     <- (dd$d3 / dd$nAdmissions) * 100
dd$share_dubbed <- (dd$dubbed / dd$nAdmissions) * 100

dd$share_ani    <- (dd$ani / dd$nFilms) * 100
dd$share_doc    <- (dd$doc / dd$nFilms) * 100
dd$share_fic    <- (dd$fic / dd$nFilms) * 100

# get colors and short names

```

```{r plot helpers, include = F}
myTheme <- function(base_family) {
  swi_theme(base_family = base_family) + 
    theme(
      #panel.ontop = TRUE,
      panel.grid.major.y=element_line(color="#b3b3b3", linetype="dashed", size=0.02),
      axis.line.x=element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
     # panel.background = element_rect(fill = "#efe9e0", color = NA),
     # plot.background = element_rect(fill = "#efe9e0", color = NA),
      strip.text = element_text(size = 12, hjust = 0, family = base_family, colour = "#595959", face = "bold"),
      plot.margin=unit(c(0, -0.1, -0.7, -0.55), "cm")
    ) 
}

myBarPlot <- function (eee, base_font, fontFactor = 1, ndigits = 0, annotations = NULL, ...) {
  gp <- ggplot(data = eee, aes(name, value, fill = color)) + 
    geom_bar_interactive(aes(tooltip = tooltip, data_id = name), stat = "identity", width = 0.95) + 
    facet_wrap(~ varName, scales = "free_y", ncol = 1) +  
    geom_text(aes(label=round(value, digits = ndigits)), position="dodge", vjust = 1.5, hjust = 0.37, 
              colour = "white", size = 2.3, family = base_font, alpha = 0.6) + 
    geom_text(aes(label=name), position=position_fill(), vjust=-0.35, hjust = 0.37, 
              colour = "white", size = 2.8, family = base_font, check_overlap = T) + 
    scale_fill_identity() + 
    scale_colour_identity() + 
    scale_y_continuous(name = "", ...) + 
    scale_x_discrete(name = "") +  
    myTheme(base_family = base_font)
  if(!is.null(annotations)) {
    gp + geom_text(
      data = annotations, aes(x, y, label = label, group = varName, colour = color), 
      family = base_font, hjust = 0, vjust = 1, size = 3.9, lineheight = 0.96, alpha = 0.75
    )  
    }
}
myIplot <- function(gp, ...) {
  ggiraph(
    code = print(gp), 
    width = 1,
    tooltip_offx = 1,
    hover_css = "fill-opacity:.3;cursor:pointer;",
    fonts = list(sans = "Open Sans Condensed"), ...)  
}

```

```{r prepare data and get some key stats}
# make data long and drop some columns
ddd <- dd %>% select(-nAdmissions, -nScreenings, -ani, -doc, -fic, -d3, -dubbed)  %>% 
  tidyr::gather(var, value, -group)

ddd <- cbind(ddd, groups[match(ddd$group, groups$key),c('name', 'color')])
ddd$name <- factor(ddd$name, levels = as.character(groups$name))

# share of EU 28 movies 
ddd %>% filter(var == "nFilms") %>% mutate(share = (value / sum(value)* 100))

# top animation countries for admissions
data %>% filter(variable == "Admissions", type == "Animated films") %>% arrange(desc(value))

# share of admissions for dubbed movies
dd %>% filter(group != 'United States') %>% 
  summarise(share_dubbed = sum(dubbed) / sum(nAdmissions)) %>% head(30)

```

```{r plot}
lang <- 'EN'

## translations
ee <- ddd
ee$name <- txt[ee$group, lang]
ee$name <- factor(ee$name, levels = txt[as.character(groups$key), lang])
ee$varName <- txt[ee$var, lang]
ee$varName <- factor(ee$varName, levels = txt[vars.ordered, lang])
ee$gr <- as.numeric(names(vars.ordered)[match(ee$var, vars.ordered)])

ee$tooltip <-  paste0(
    '<h4>', as.character(ee$name), '</h4><div class = "tp"> ', 
    round(ee$value ,1), '</div>'
)

# annotations 
anno <- annot
anno$label <- txt[anno$code, lang]
anno$varName <- txt[gsub("^annot.", "", anno$code), lang]
anno$varName <- factor(anno$varName,  levels = txt[vars.ordered, lang])
anno$color <- "black"

# sting wrap
for(i in 1:nrow(anno)) {
  anno[i, 'label'] <- paste0(strwrap(anno[i, 'label'], width = anno[i, "width"]), collapse = "\n")
}


## Generate static charts 
keys <- paste0("annot.", ee %>% filter(gr == 1) %>% select(var) %>% unlist(use.names = F) %>% unique())
gp <- myBarPlot(
  ee %>% filter(gr == 1), 
  base_font = txt['base.font', lang], 
  annotations = anno %>% filter(code %in% keys)
)

keys <- paste0("annot.", ee %>% filter(gr == 2) %>% select(var) %>% unlist(use.names = F) %>% unique())
gp2 <- myBarPlot(ee %>% filter(gr == 2), 
          base_font = txt['base.font', lang],
          annotations = anno %>% filter(code %in% keys),
          labels = function(x) paste0(x,'%'))


keys <- paste0("annot.", ee %>% filter(gr == 3) %>% select(var) %>% unlist(use.names = F) %>% unique())
gp3 <- myBarPlot(ee %>% filter(gr == 3), 
          base_font = txt['base.font', lang],
          annotations = anno %>% filter(code %in% keys),
          labels = function(x) paste0(x,'%'))


# myIplot(gp)
# myIplot(gp2, height_svg = 10)
#ggiraph(code = print(gp),   fonts = list(sans = "Open Sans Condensed"))

 source <- paste0(
    txt['source', lang], ": ", 
    htmlLink("https://www.pxweb.bfs.admin.ch/Selection.aspx?px_language=en&px_db=px-x-1602010000_200&px_tableid=px-x-1602010000_200%5Cpx-x-1602010000_200.px&px_type=PX", txt['source.name', lang]), 
    " | ", htmlLink("https://twitter.com/duc_qn", '@duc_qn'),
    " | ", htmlLink("http://www.swissinfo.ch", 'swissinfo.ch')  )
  
  outfile <- paste0("moviesInSwissCinema_", lang, ".html")
  save_html(
    tags$html(
      tags$head(includeHTML("styles.html")),
      tags$body(    
        h2(txt["title", lang]),
        div(class = "descr", HTML(paste0(txt["descr", lang]))),
        div(class="container", myIplot(gp, height_svg = facet_height * 3)),
                HTML("<br>"),
        h2(HTML(txt["title.b", lang])),
        div(class = "descr", HTML(paste0(txt["descr2", lang]))),
        div(class="container", myIplot(gp2, height_svg = facet_height * 3)),
        HTML("<br>"),
        h2(HTML(txt["title.c", lang])),
        div(class = "descr", HTML(paste0(txt["descr2", lang]))),
        div(class="container", myIplot(gp3, height_svg = facet_height * 2)),
        div(id = "cite", HTML(source)),
        div(id = "footer", HTML(txt["footer", lang])),
        HTML(iframeresizer)  
      )), file = outfile, libdir = "js", background = "#e6e6e6"
  )  
  

```